### ISSUE TITLE
Request failed with status code 502

### ISSUE THREAD

**Issue by AlexanderXIV** [marlon360/rki-covid-api#131]
First of all, I want to thank for this great API and the care behind it. However, when I try to call 'https://api.corona-zahlen.org/map/districts' I get the error message 502.

``` js
Error: Request failed with status code 502
    at createError (/usr/src/app/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/usr/src/app/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/usr/src/app/node_modules/axios/lib/adapters/http.js:260:11)
    at IncomingMessage.emit (events.js:326:22)
    at IncomingMessage.EventEmitter.emit (domain.js:506:15)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

EDIT: Just now it's working again.

**Comment by marlon360** [comment]
Closing this now.
Comment here when you see this error again.
Thank you!
