### ISSUE TITLE
Frozen not working

### ISSUE THREAD

**Issue by marcusraitner** [marlon360/rki-covid-api#265]
I get the following error:

`2021-08-05 06:57:57: Getting frozen data for ags: https://api.corona-zahlen.org/districts/09175/history/frozen-incidence/34
2021-08-05 06:58:00: {"error":{"message":"An error occurred.","details":"Cannot read property 'toString' of undefined","stack":"TypeError: Cannot read property 'toString' of undefined\n    at /usr/src/app/src/data-requests/frozen-incidence.ts:44:34\n    at Array.map (<anonymous>)\n    at Object.<anonymous> (/usr/src/app/src/data-requests/frozen-incidence.ts:42:24)\n    at Generator.next (<anonymous>)\n    at fulfilled (/usr/src/app/dist/data-requests/frozen-incidence.js:5:58)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)"}}`

Seems to me that the excel source once again has somehow changed.

**Comment by Rubber1Duck** [comment]
see #264

**Comment by marcusraitner** [comment]
Thanks! Just looked at the headlines and didn't conclude that this one was also about frozen.
