### ISSUE TITLE
/germany endpoint returns error

### ISSUE THREAD

**Issue by zusorio** [marlon360/rki-covid-api#272]
```
http get https://api.corona-zahlen.org/germany
HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
Connection: keep-alive
Content-Length: 291
Content-Type: application/json; charset=utf-8
Date: Thu, 26 Aug 2021 16:13:53 GMT
ETag: W/"123-6UJsK+aqHW77L1xZ0Ntg5Tyu28c"
Retry-After: 28.746
Server: nginx/1.19.3
Strict-Transport-Security: max-age=31536000
Vary: Accept-Encoding
X-Powered-By: Express
X-RateLimit-Limit: 15
X-RateLimit-Remaining: 13
X-RateLimit-Reset: Thu Aug 26 2021 16:14:22 GMT+0000 (Coordinated Universal Time)

{
    "error": {
        "details": "connect ETIMEDOUT 195.128.103.247:443",
        "message": "An error occurred.",
        "stack": "Error: connect ETIMEDOUT 195.128.103.247:443\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16)\n    at TCPConnectWrap.callbackTrampoline (internal/async_hooks.js:126:14)"
    }
}
```

**Comment by Rubber1Duck** [comment]
i think that issue can be closed, it looks like that was another temporary problem, or do you have still that problem?

**Comment by zusorio** [comment]
It's working again

**Comment by mindbreaker** [comment]
Got the same message again:


`{"error":{"message":"An error occurred.","details":"connect ETIMEDOUT 195.128.103.247:443","stack":"Error: connect ETIMEDOUT 195.128.103.247:443\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16)\n    at TCPConnectWrap.callbackTrampoline (internal/async_hooks.js:126:14)"}}`

**Comment by shinebar1001** [comment]
It's working again. Suricata (IDS/IDP) detected some traffic as malicious and blocked the connection.
