### ISSUE TITLE
Yet another 502 Bad Gateway

### ISSUE THREAD

**Issue by kalaschnik** [marlon360/rki-covid-api#301]
Every endpoint either gives me a 502 Bad Gateway or I get

```
{"error":{"message":"An error occurred.","details":"connect ETIMEDOUT 195.128.103.247:443","stack":"Error: connect ETIMEDOUT 195.128.103.247:443\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16)\n    at TCPConnectWrap.callbackTrampoline (internal/async_hooks.js:126:14)"}}
```

Endpoints tested:
- https://api.corona-zahlen.org/districts/02000
- https://api.corona-zahlen.org/germany

Any ideas?

**Comment by shinebar1001** [comment]
Mea culpa - shoud be fixed in a few minutes. Firewall-Issue.

**Comment by kalaschnik** [comment]
Yep, all good again!
