### ISSUE TITLE
Error on frozen-incidence history

### ISSUE THREAD

**Issue by csigritz** [marlon360/rki-covid-api#346]
Currently frozen-incidence history endpoint results in an error:
 
URL: https://api.corona-zahlen.org/states/BY/history/frozen-incidence/14

Error:
```json
{
    "error": {
        "message": "An error occurred.",
        "details": "Cannot read properties of undefined (reading 'v')",
        "stack": "TypeError: Cannot read properties of undefined (reading 'v')\n    at /workspace/src/data-requests/frozen-incidence.ts:115:34\n    at Generator.next (<anonymous>)\n    at fulfilled (/workspace/dist/data-requests/frozen-incidence.js:5:58)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"
    }
}
```

Maybe this is related to the closed issue this morning: https://github.com/marlon360/rki-covid-api/issues/345
Or just a coincidence?

**Comment by Rubber1Duck** [comment]
The RKI changed once more the layout of the Excelsheet :-(
