### ISSUE TITLE
Frozen Incidence URL hat sich geändert

### ISSUE THREAD

**Issue by mklippel** [marlon360/rki-covid-api#393]
Hallo,

ich benutze die Frozen incidence der API. Soweit ich das verstehe wird dabei ja eine Excel Datei runter geladen und die einzelnen Sheets dabei auseinander gepflückt und diese Daten werden dann zur Verfügung gestellt.

Mein Aufruf: https://api.corona-zahlen.org/districts/11111/history/frozen-incidence/7
Dabei kommt folgender Fehler:
`
{
error: {
message: "An error occurred.",
details: "Invalid HTML: could not find <table>",
stack: "Error: Invalid HTML: could not find <table>
    at Object.html_to_book [as to_workbook] (/workspace/node_modules/xlsx/xlsx.js:20308:39)
    at parse_xlml_xml (/workspace/node_modules/xlsx/xlsx.js:16530:26)
    at parse_xlml (/workspace/node_modules/xlsx/xlsx.js:17251:53)
    at Object.readSync [as read] (/workspace/node_modules/xlsx/xlsx.js:21888:21)
    at /workspace/src/data-requests/frozen-incidence.ts:30:23
    at Generator.next (<anonymous>)
    at fulfilled (/workspace/dist/data-requests/frozen-incidence.js:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)"
}
}
`

Soweit ich sehe, gibt es diese Excel Datei nicht mehr unter der URL wie sie im Quelltext steht:
https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Daten/Fallzahlen_Kum_Tab.xlsx?__blob=publicationFile

Es wurde aufgeteilt in aktuelle Zahlen und archivierte Zahlen:

**Aktuelle Zahlen**
https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Daten/Fallzahlen_Kum_Tab_aktuell.xlsx?__blob=publicationFile

**Archiv Zahlen**
https://www.rki.de/DE/Content/InfAZ/N/Neuartiges_Coronavirus/Daten/Fallzahlen_Kum_Tab_Archiv.xlsx?__blob=publicationFile

Bitte passt das doch mal an, wenn Zeit ist. 
Ich würde die URL der aktuellen Zahlen für die frozen incidence nehmen.

**Comment by Rubber1Duck** [comment]
is in work .............. see #392
