### ISSUE TITLE
Docker Image shows no District figures

### ISSUE THREAD

**Issue by cc13com** [marlon360/rki-covid-api#449]
Hello,

since I'm running in an issue showing the "District" figures (https://api.my_domain.xxx/districts):

```
{"error":{"message":"An error occurred.","details":"Cannot read properties of undefined (reading 'attributes')","stack":"TypeError: Cannot read properties of undefined (reading 'attributes')\n    at /usr/src/app/src/data-requests/districts.ts:114:47\n    at Generator.next (<anonymous>)\n    at fulfilled (/usr/src/app/dist/data-requests/districts.js:5:58)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"}}
```

i pulled the docker-image but running in the same issue. Is there an image update neccessary? All other endpoints looking good so far.

**Comment by cc13com** [comment]
All good, another container restart "solved" the issue.
