### ISSUE TITLE
Error when accessing data of just one state

### ISSUE THREAD

**Issue by codingcat2468** [marlon360/rki-covid-api#507]
Hi,
first of all: great work, the API is working again!
I just found one problem:
The [/states Endpoint](https://api.corona-zahlen.org/states) works without problems, but when I try to access just one specific state (for example [/states/HE](https://api.corona-zahlen.org/states/HE)), I get this error: 
```
{
	"error": {
		"message": "An error occurred.",
		"details": "Cannot read properties of undefined (reading 'id')",
		"stack": "TypeError: Cannot read properties of undefined (reading 'id')\n    at /usr/src/app/src/responses/states.ts:144:20\n    at Array.filter (<anonymous>)\n    at /usr/src/app/src/responses/states.ts:143:21\n    at Generator.next (<anonymous>)\n    at fulfilled (/usr/src/app/dist/responses/states.js:5:58)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"
	}
}
```

**Comment by Rubber1Duck** [comment]
Thanks for the error report, will have a look on it.
