### ISSUE TITLE
TypeError on most endpoints

### ISSUE THREAD

**Issue by codingcat2468** [marlon360/rki-covid-api#509]
It seems there is a problem with the data parser... Most Endpoints show a similar error.
This is the response of the germany endpoint:
```
{
	"error": {
		"message": "An error occurred.",
		"details": "Cannot read properties of undefined (reading 'weekIncidence')",
		"stack": "TypeError: Cannot read properties of undefined (reading 'weekIncidence')\n    at /usr/src/app/src/responses/germany.ts:102:4\n    at Generator.next (<anonymous>)\n    at fulfilled (/usr/src/app/dist/responses/germany.js:5:58)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"
	}
 }
```
and the states endpoint
```
{
	"error": {
		"message": "An error occurred.",
		"details": "Cannot read properties of undefined (reading 'weekIncidence')",
		"stack": "TypeError: Cannot read properties of undefined (reading 'weekIncidence')\n    at /usr/src/app/src/responses/states.ts:111:6\n    at Array.map (<anonymous>)\n    at /usr/src/app/src/responses/states.ts:104:32\n    at Generator.next (<anonymous>)\n    at fulfilled (/usr/src/app/dist/responses/states.js:5:58)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"
	}
}
```

**Comment by Rubber1Duck** [comment]
Unfortnatly i am Not at home and have no Equipment to Debugger this!
Will be at home tomorrow or thoursday!
Bevor ich have Not Chance to Patch this!
I am sorry!

**Comment by Rubber1Duck** [comment]
all is running again!
